import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/shared/footer/Footer";
import Header from "@/components/HeaderNav/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "KART Podology",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col ${geistSans.variable} ${geistMono.variable} bg-[#F5F5F5CC]">
        <Header />

        <main className="flex-grow container">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
