import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "../shared/footer/Footer";
import Header from "../components/HeaderNav/Header";
import AppProvider from "../shared/app-provider/AppProvide";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col ${geistSans.variable} ${geistMono.variable} bg-[#F5F5F5CC]">
        <div id="modal" />
        <AppProvider >
          <Header />

          <main className="flex-grow container pt-[160px]! ">
            {children}
          </main>
          <div className="container">

            <Footer />
          </div>
        </AppProvider>
      </body>
    </html>
  );
}
