import { Fira_Sans } from "next/font/google";
import "../globals.css";
import Footer from "../../shared/footer/Footer";
import Header from "../../shared/nav-section/Header";
import AppProvider from "../../shared/app-provider/AppProvide";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "../../i18n/routing";
import { notFound } from "next/navigation";
import { getMessages } from "next-intl/server";
import LocaleRedirector from "../../shared/redirector/LocaleRedirector";

const firaSans = Fira_Sans({
  variable: "--font-fira-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params;

  let messages;
  try {
    messages = await getMessages();
  } catch (error) {
    notFound();
  }

  return (
    <html lang={locale} className={firaSans.variable}>
      <body className="min-h-screen flex flex-col bg-[#F5F5F5CC]">
        <AppProvider>
          <NextIntlClientProvider locale={locale}>
            <LocaleRedirector />
            <Header />
            <main className="flex-grow container pt-[90px]! xl:pt-[160px]!">
              {children}
            </main>
            <div id="modal" />
          </NextIntlClientProvider>
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}